"""
Django settings for trade project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
# settings.py 最顶部（必须在其他导入之前，避免先触发报错）
from django.utils.encoding import force_str
import django.utils.encoding

# 将force_str映射为smart_text，供第三方库导入使用
django.utils.encoding.smart_text = force_str
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4jp9r_#yxn!j5i4*a&ij1i7pgce7)zt9jtsz6^st#z3kgcg#vc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #用户模块注册
     'users.apps.UsersConfig',
    #首页应用注册
     'home.apps.HomeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trade.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trade.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'house_trading_system_final',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

CACHES = {
    "default": {#默认设置
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "",
        }
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "",

        }
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"# Password validation

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#redis日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,#是否禁用已经存在的日志服务器
    'formatters': {#日志信息显示的格式
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters': {#对日志进行过滤
        'require_debug_true': {#django在debug模式下才会输出日志
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {#日志处理的方法
        'console': {#向终端控制台输出日志
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {#向文件输出日志
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename':os.path.join(BASE_DIR,'logs/trade.log'),#日志文件的位置
            'maxBytes': 300*1024*1024,
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {#日志器
        'django': {#定义了一个名为django的日志器
            'handlers': ['console', 'file'],#可以同时向文件与终端输出日志
            'propagate': True,#是否继续传递日志信息
            'level': 'INFO',#日志器接收的最低日志级别
        },
    }
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


#静态文件加载路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),

]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#替换django默认指定的User，需要指定本项目自定义的用户模型类
#配置信息：'子应用名.模型类名'
AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/login/'

#3、设置上传的头像保存到media
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')

import os

# PDF生成配置
WKHTMLTOPDF_CMD = os.path.join(os.path.dirname(__file__), 'bin', 'wkhtmltopdf.exe')  # Windows
#设置头像统一访问路径
MEDIA_URL = '/media/'