# Generated by Django 4.2.27 on 2026-01-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mobile_user_phone_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
    ]
