# Generated by Django 4.2.27 on 2026-01-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_license',
            field=models.CharField(blank=True, max_length=50, verbose_name='中介执照号'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='中介联系电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_real_estate_agent',
            field=models.BooleanField(default=False, verbose_name='是否为房屋中介'),
        ),
    ]
