# Generated by Django 4.2.27 on 2026-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
