# Generated by Django 4.2.27 on 2026-01-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_city_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
