# Generated by Django 4.2.27 on 2026-01-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_city_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
