# Generated by Django 4.2.27 on 2026-01-07 06:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_city_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='city_images/%Y%m%d')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.city')),
            ],
            options={
                'verbose_name': '城市图片管理',
                'verbose_name_plural': '城市图片管理',
                'db_table': 'td_city_images',
            },
        ),
    ]
