# Generated by Django 4.2.27 on 2026-01-07 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_cityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='执照号')),
                ('company', models.CharField(max_length=100, verbose_name='所属公司')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='个人介绍')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '房屋中介管理',
                'verbose_name_plural': '房屋中介管理',
                'db_table': 'td_real_estate_agents',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', '买方'), ('seller', '卖方')], max_length=10, verbose_name='角色')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.realestateagent', verbose_name='中介')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city', verbose_name='房产')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录管理',
                'verbose_name_plural': '交易记录管理',
                'db_table': 'td_transactions',
            },
        ),
    ]
