# Generated by Django 4.2.27 on 2026-01-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_realestateagent_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-created_at',), 'verbose_name': '城市分类管理', 'verbose_name_plural': '城市分类管理'},
        ),
    ]
