# Generated by Django 4.2.27 on 2026-01-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='home.realestateagent', verbose_name='关联中介'),
        ),
    ]
