# Generated by Django 4.2.27 on 2026-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_city_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='交易金额'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_name',
            field=models.CharField(default='', max_length=100, verbose_name='买家姓名'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_phone',
            field=models.CharField(default='', max_length=20, verbose_name='买家电话'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_data',
            field=models.JSONField(blank=True, null=True, verbose_name='合同数据'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property_address',
            field=models.CharField(default='', max_length=500, verbose_name='房产地址'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='房产价格'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property_title',
            field=models.CharField(default='', max_length=200, verbose_name='房产标题'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_name',
            field=models.CharField(default='', max_length=100, verbose_name='卖家姓名'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_phone',
            field=models.CharField(default='', max_length=20, verbose_name='卖家电话'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='completed', max_length=20, verbose_name='状态'),
        ),
    ]
