# Generated by Django 4.2.27 on 2026-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_transaction_amount_transaction_buyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=50, unique=True, verbose_name='房屋编号')),
                ('address', models.CharField(max_length=200, verbose_name='房屋地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='房屋价格')),
                ('area', models.FloatField(verbose_name='房屋面积')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已售出/删除')),
            ],
            options={
                'verbose_name': '房屋信息',
                'verbose_name_plural': '房屋信息',
            },
        ),
    ]
