# Generated by Django 4.2.27 on 2026-01-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='是否已售出'),
        ),
    ]
