# Generated by Django 4.2.27 on 2026-01-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_city_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city', verbose_name='房产'),
        ),
    ]
