# Generated by Django 4.2.27 on 2026-01-08 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_transaction_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='合同编号')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='买方姓名')),
                ('buyer_idcard', models.CharField(max_length=18, verbose_name='买方身份证')),
                ('seller_name', models.CharField(max_length=50, verbose_name='卖方姓名')),
                ('seller_idcard', models.CharField(max_length=18, verbose_name='卖方身份证')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city', verbose_name='关联房源')),
            ],
            options={
                'verbose_name': '购房合同',
                'verbose_name_plural': '购房合同',
            },
        ),
    ]
