# Generated by Django 4.2.27 on 2026-01-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已售出'),
        ),
    ]
